repos:
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.3
      hooks:
        - id: seed-isort-config
    - repo: https://github.com/timothycrosley/isort
      rev: 4.3.21
      hooks:
        - id: isort
    -  repo: https://github.com/psf/black
       rev: 19.10b0
       hooks:
        - id: black
          files: scripts/
    - repo: https://github.com/doublify/pre-commit-rust
      rev: master
      hooks:
          - id: cargo-check
            args: ["--manifest-path", "app/Cargo.toml"]